# -*- coding: utf-8 -*-
"""pccp기출1번.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iYCwcBMssKiMCoVhvDbDEPbKgG3OgwMt
"""

def solution(bandage, health, attacks):
    #현재시간 변수
    now=1
    #현재 생존여부
    live=True
    #현재 체력
    now_health=health
    #공격받은 여부
    give_attack=False
    #연속 붕대시간
    bandage_time=1
    #살아있는동안
    while live:
        #공격여부 탐색
        for y in attacks:
            if (now == y[0]):
                now_health=now_health-y[1]
                bandage_time=1
                if (now==attacks[-1][0] and now_health>0):
                    return now_health
                now=now+1
                give_attack=True
                break
        #죽었을 때
        if (now_health<=0):
            live = False
        else:
            if(not give_attack):
                now_health=min(now_health+bandage[1],health)
                if (bandage_time>=bandage[0]):
                    now_health=min(now_health+bandage[2],health)
                    bandage_time=1
                else:
                    bandage_time=bandage_time+1
                now=now+1
            give_attack=False
    return -1